--- #this is create-user playbook
- name: my test playbook
  hosts: webservers
  become: yes
  user: ansible
  connection: ssh


  tasks: 
    - name: creating a user
      user: 
        name: Benarjee 
