--- # installation software
- hosts: webservers
  user: ansible
  connection: ssh
  become: yes
  tasks:
    - name: install package into hosts
      yum: 
       name: docker
       state: installed
