--- #Install multiple software packages
- hosts: webservers
  become: yes
  connection: ssh
  user: ansible

  tasks:
    - name: install packages
      yum:
        name: [ 'git', 'which', 'docker', 'mysql', 'tree','wget', 'httpd','java']
        state: installed
